version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: crmgo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: crmgo_demo
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - crmgo_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  crmgo_mysql_data:
